export {
  ArrowDownTrayIcon,
  ArrowPathIcon,
  ArrowUpTrayIcon,
  ArrowsPointingOutIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ChatBubbleLeftRightIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  Cog6ToothIcon,
  DocumentDuplicateIcon,
  DocumentPlusIcon,
  EyeIcon,
  FolderOpenIcon,
  GlobeAltIcon,
  MapPinIcon,
  PauseIcon,
  PhotoIcon,
  PlayIcon,
  RectangleStackIcon,
  SwatchIcon,
} from "@heroicons/react/24/outline";
